import { Poppins } from 'next/font/google'
import './global.css'
import Script from 'next/script'
import SessionWrapper from './components/sessionWrapper'


const inter = Poppins({ subsets: ['latin'], weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
const tailClass = 'w-full h-screen flex bg-[#313338] overflow-hidden'
const combinedClass = `${inter.className} ${tailClass}`

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <SessionWrapper>
        <body className={combinedClass}>
          {children}
        </body>
      </SessionWrapper>
      <Script src='https://kit.fontawesome.com/60734bdbf3.js' />
    </html>
  )
}
